---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg
spec:
  selector:
    matchLabels:
      postgresql: cnpg
  podMetricsEndpoints:
    - port: metrics
