---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/backend/
  - ./namespace.yaml
patches:
  - target:
      version: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: backend-electricilies
    path: ./patches/electricilies.ks.yaml
  - target:
      version: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: backend-electricilies
    patch: |- # language: yaml
      - op: add
        path: /spec/dependsOn/-
        value:
          - name: app-keycloak
