---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name cnpg
spec:
  instances: 1
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: false
  bootstrap:
    initdb:
      database: electricilies
      secret:
        name: keycloak-auth
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: *name
