---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name cnpg
spec:
  instances: 1
  imageName: paradedb/paradedb:17-v0.18.11
  env:
    - name: TZ
      value: Asia/Ho_Chi_Minh
  storage:
    size: 100Mi
  monitoring:
    enablePodMonitor: false
  bootstrap:
    initdb:
      database: electricilies
      secret:
        name: *name
      # Take from https://github.com/paradedb/charts/blob/dev/charts/paradedb/templates/_bootstrap.tpl
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS pg_search;
        - CREATE EXTENSION IF NOT EXISTS pg_ivm;
        - CREATE EXTENSION IF NOT EXISTS vector;
        - CREATE EXTENSION IF NOT EXISTS postgis;
        - CREATE EXTENSION IF NOT EXISTS postgis_topology;
        - CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
        - CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;
        - ALTER DATABASE "electricilies" SET search_path TO public,paradedb;
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS pg_search;
        - CREATE EXTENSION IF NOT EXISTS pg_ivm;
        - CREATE EXTENSION IF NOT EXISTS vector;
        - CREATE EXTENSION IF NOT EXISTS postgis;
        - CREATE EXTENSION IF NOT EXISTS postgis_topology;
        - CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
        - CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;
        - ALTER DATABASE template1 SET search_path TO public,paradedb;
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: *name
