---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name cnpg
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-system-trixie
  env:
    - name: TZ
      value: Asia/Ho_Chi_Minh
  storage:
    size: 100Mi
  monitoring:
    enablePodMonitor: false
  bootstrap:
    initdb:
      database: electricilies
      secret:
        name: *name
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: *name
