# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cnpg
stringData:
  username: ENC[AES256_GCM,data:UNRYrr6FMg+M7CuzqQ==,iv:Kr+nL2W8DWBAnnHdi42Oo9MMqM7Z8kqk3miuQcxcNIY=,tag:Ak3axvaoMBl3sPDRr9iq5w==,type:str]
  password: ENC[AES256_GCM,data:PeFgSHMK8U22OaRhhA==,iv:uLcQ+5f5jvPr3CN8p9NVvjtRs87XW2cDNH0AZ2MHHDY=,tag:G8VvNUSR4hCbiGb3vev49g==,type:str]
sops:
  age:
    - recipient: age19q9u5nz7xrtd8qxq3n089n663vznw2r3ayzzdc30zxx3jrezaalseupkkv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaR2tmbk4vcjJXR3YvVXRq
        b2VGenN4K2ZnMkNWUzMyVXVYU0o0V1FDRXdnCmZkaCtlQ09VMllaU3c1NWxpTWlM
        Z1cxVk1uUjRvQnpSdWdJbGovOTFxK28KLS0tIE5GYk9IaVdUaWFVdXNPbFoxUW16
        TWUvOTlmUWZtVzcvYjRxQzUyK3Fzd0UKtRVMEURpZOKA1lH5BHYADIhlb+HjRD5Y
        acw7H8FKaFt9UWDJ+9rolyiZx/EP/BhAKAPDl54I9hfq5/o0+Ls/uw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-18T17:52:21Z"
  mac: ENC[AES256_GCM,data:CR+D7Hj3WL7Mf6Q+Q4o4h1YtikMQ6RW3K7aPAksvBIIm+HNdUuQQQ5MHG4ggFmfCQJ3b2OjUT7IIThe+GR/q2NLO9we1OV3lZUXqSibFv83OyGJci27m7QhJQahkgx+EdpFxcqCRTZhejuiQlSdhUd0GZZpPT56m9dgyImuc1oM=,iv:4L5mAG0hdZXT9UtITgK1wDip+/7pV5k0ePUAM7go5AY=,tag:qdX6pOzlKy8jw3iGGApggw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
