nameReference:
  - version: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    fieldSpecs:
      - path: spec/dependsOn/name
        version: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
