---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name electricilies
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    spec:
      containers:
        - name: *name
          image: ghcr.io/electricilies/frontend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: electricilies-keycloak
          readinessProbe: &health
            httpGet:
              path: /api/health
              port: 3000
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            <<: *health
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 10m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi
