# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: electricilies-keycloak
stringData:
  AUTH_KEYCLOAK_ID:
  AUTH_KEYCLOAK_SECRET:
  AUTH_KEYCLOAK_ISSUER:
