---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name electricilies
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    spec:
      containers:
        - name: *name
          image: ghcr.io/electricilies/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: ELASTIC_URL
              value: http://elastic-es-http.elastic:9200
          envFrom:
            - secretRef:
                name: electricilies-elastic
            - secretRef:
                name: electricilies-keycloak
            - secretRef:
                name: electricilies-postgres
          readinessProbe: &health
            httpGet:
              path: /api/health
              port: 8080
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            <<: *health
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 200Mi
