---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name electricilies
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector: {}
  template:
    spec:
      containers:
        - name: *name
          image: ghcr.io/electricilies/backend:latest
          ports:
            - containerPort: 8080
          readinessProbe: &health
            httpGet:
              path: /api/health
              port: 8080
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            <<: *health
            periodSeconds: 10
            failureThreshold: 3
