---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name electricilies
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    spec:
      containers:
        - name: *name
          image: ghcr.io/electricilies/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: cnpg.postgres
            - name: DB_DATABASE
              value: *name
            - name: DB_PORT
              value: "5432"
            - name: GIN_MODE
              value: release
          envFrom:
            - secretRef:
                name: electricilies-keycloak
            - secretRef:
                name: electricilies-postgres
          readinessProbe: &health
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            <<: *health
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 200Mi
  selector: {}
