---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backend-electricilies
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: electricilies
  path: app/base/backend/electricilies/
  dependsOn:
    - name: postgres-migrations
  decryption:
    provider: sops
    secretRef:
      name: electricilies-sops-age
