# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: electricilies-postgres
stringData:
  DB_USERNAME: ENC[AES256_GCM,data:Yuxn8BqGhqGXIBsTzA==,iv:/v6Bj98HyC135w1cgaEMX6YqZwyjExHWZFsnGSRwJnk=,tag:Fc2Rj9V3FvYsb7rLXg0C6g==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:XiWRSvIjaSDVObaetA==,iv:NjkaaZ3xlucysT3hl5LhoIdsjLczBUlp2NcGi7j6Bgk=,tag:xlTQ6l2ZiRBitMAVZ13hJw==,type:str]
  DB_DATABASE: ENC[AES256_GCM,data:xg9COEg5Hp1PoBRfVQ==,iv:bUZb6FKcISmucrm92BqX3CMKQebwYCvJVQCcMJ2qs64=,tag:uPfOUegwykEYJs27kIDcLg==,type:str]
sops:
  age:
    - recipient: age19q9u5nz7xrtd8qxq3n089n663vznw2r3ayzzdc30zxx3jrezaalseupkkv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSmFwUUFtcFV5eEIxSXhC
        bk5INmNIVkF2R0ZLMDN4eC9rSEpidWVmdUFzCjRjeVBBcXBGTmZFcFM3c0dZWVNj
        bEw3Q3psNkVUMEpQbCtBVjdCeGlNSDQKLS0tIHBOcS8xWmxwTXNtZnJDaEJlMGUx
        dEl1TG5JRjVQNkJHQVljSll1TVFjY2MK38tjz6CbAFNlr6Aa/rBVxabPrgP6WLCx
        uBnz3cuNW0qG0B21YdpQID1v5tLi69elQplBr6lRA5vBJEZ45g6euA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-19T03:41:14Z"
  mac: ENC[AES256_GCM,data:mxUTftBnzez2Nbjez65UKGHGNMJqbStsRZDqANCm995ygNYk4nxMDwpTUe2TSdP6K+7ysySI6/sx3dLy2HlLfWvZbQhP/aYlWKwcZSG2LOcn+eJb5jwWNFJb8N40Z32IhM4G5/jCMr4K9UI25FIcK4RVETtRhhYzhRFjt6bGwic=,iv:Lle7ydbbeM7aA1f71+6OXCu4yEuNH/ABnyrcZkl1bY0=,tag:mR10/+zPVb175k3iUP7Gkg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
