---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name electricilies
spec:
  template:
    metadata:
      labels:
        alloy.kevinnitro/scrape: "1"
    spec:
      containers:
        - name: *name
          env:
            - name: DB_HOST
              value: cnpg.electricilies-dev-postgres
            - name: KEYCLOAK_ISSUER
              value: electricilies-dev
            - name: S3_ENDPOINT
              value: http://minio.electricilies-dev-backend:80
