---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: electricilies-dev-backend
resources:
  - ../../../base/backend/electricilies/
  - ./httproute.yaml
labels:
  - pairs:
      alloy.kevinnitro/scrape: "1"
patches:
  - path: ./deployment.patch.yaml
images:
  - name: ghcr.io/electricilies/backend
    digest: sha256:a25f7361da9b53f76783843603a3029ac61a2aa8234eb34ec9267845e4f7e997
