---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: electricilies-dev-backend
resources:
  - ../../../base/backend/electricilies/
  - ./httproute.yaml
labels:
  - pairs:
      app.kubernetes.io/name: electricilies-backend
    includeSelectors: true
patches:
  - path: ./deployment.patch.yaml
images:
  - name: ghcr.io/electricilies/backend
    digest: sha256:c9786cafe2ef560667bd935a6e2c836827a9cb77b53ce46b831cc51409eca4cf
