---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name electricilies
spec:
  template:
    spec:
      containers:
        - name: *name
          env:
            - name: BACKEND_ENDPOINT
              value: electricilies.electricilies-dev-backend
