---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/postgres/
  - ./namespace.yaml
patches:
  - path: ./cnpg.ks.patch.yaml
  - path: ./migration.ks.patch.yaml
