---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/postgres/ks.yaml
patches:
  - target:
      version: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
    path: ./patches/ks.yaml
