---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic-elastic
  namespace: flux-system
spec:
  path: app/kevinnitro-homelab-dev/elastic/elastic/
  postBuild:
    substituteFrom:
      - kind: Secret
        name: setting
      - kind: ConfigMap
        name: setting
