# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: electricilies-keycloak
stringData:
  AUTH_KEYCLOAK_SECRET: ENC[AES256_GCM,data:WWBv,iv:tG3GuQd+BuF5LpGjFipH3RwZ5LFRDLdLJ+S5x+6GKSk=,tag:OjC/S9ud1RD3ktzKP7SCmg==,type:str]
sops:
  age:
    - recipient: age19q9u5nz7xrtd8qxq3n089n663vznw2r3ayzzdc30zxx3jrezaalseupkkv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMmk4Y0NPaXB0cFdQcmxv
        NFNKK3hjZURwbDZqNVBKamdHMFozRSt0TmlJCkpTUTYrTWgrSFhXMzh1MTE3QWk3
        WHJ1V2I0bnNVUmxidVh0TDNQQlhiWVkKLS0tICtWUE9qcThDMkQ5SlVSWjFnOFp1
        b2w1UTI0cFJNdyt4SjB0WGFRbkVSRVkKdFd0l+X7sjnzu3hNmFLIOiFYqzn2yE+K
        Y6JzdguNWKvrU476ixr1NAQect/TehPd/KLG/GUsn23aoTYRPTin0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T03:52:15Z"
  mac: ENC[AES256_GCM,data:GD7360ZEwHf7kX1oRpplHcmnCFFreODfosPTicEGkEU3/y9rRR96QeYxgevP5Wm89FottWjuQX28ZeD00XpOh0tvZFWSL7pzBnD4bvv91xN1A0hkLQG88v5dmoH82JCb3z0iOPiIhKoKZVdJTqs0lWYV6IZThRduVG3dCdVPYEo=,iv:WKORuEm+rkfbZXKCSA+sfjURXth/8mhzwn44G8/x7cg=,tag:dMa3WSevPrtwRM9+ET1RAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
