---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: electricilies-dev-frontend
resources:
  - ../../../base/frontend/electricilies/
  - ./httproute.yaml
patches:
  - path: ./deployment.patch.yaml
  - path: ./keycloak.patch.secret.sops.yaml
images:
  - name: ghcr.io/electricilies/frontend
    digest: sha256:436ae1263689c018778433dec71d818949b38f154d6e08709466b638a0e8e87d
