---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: electricilies-dev-frontend
resources:
  - ../../../base/frontend/electricilies/
  - ./httproute.yaml
patches:
  - path: ./deployment.patch.yaml
  - path: ./keycloak.patch.secret.sops.yaml
images:
  - name: ghcr.io/electricilies/frontend
    digest: sha256:6527376553982f3119bfcd2f09acaf3e7561f2c1dc99fc767591d0e803b881ee
