---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: electricilies-dev-frontend
resources:
  - ../../../base/frontend/electricilies/
  - ./httproute.yaml
patches:
  - path: ./deployment.patch.yaml
  - path: ./keycloak.patch.secret.sops.yaml
images:
  - name: ghcr.io/electricilies/frontend
    digest: sha256:26c49b33c9ba94d258dea064e18b42cb5d8aa3dec60e979ba8f1fdfd2b64ae2e
