---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/job-batch-v1.json
apiVersion: batch/v1
kind: Job
metadata:
  name: create-bucket
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: create-bucket
          image: minio/mc:latest
          command:
            - /usr/bin/sh
            - -c
          args:
            - |- # language: sh
              mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
              mc mb local/electricilies || true &&
              mc policy set public local/electricilies
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-config
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-config
                  key: MINIO_ROOT_PASSWORD
