---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: electricilies-dev-postgres
resources:
  - ../../../base/postgres/migration/
images:
  - name: ghcr.io/electricilies/migrate
    digest: sha256:16d2f2df1ce3db033a4e85f16efefc5f9ce2c9d364fd0edf14e4acf15d2b2fb3
