name: Call Update Image

on:
  workflow_call:
    inputs:
      electricilies-bot-app-id:
        required: true
        type: string
      images:
        required: true
        type: string
        description: What image(s) to update in this org, separated by ","
      environments:
        required: false
        type: string
        description: What environment(s) to update, separated by ",", default to all (Not handled yet)
    secrets:
      electricilies-bot-private-key:
        required: true

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v2
        with:
          private-key: ${{ secrets.electricilies-bot-private-key }}
          app-id: ${{ inputs.electricilies-bot-app-id }}
          owner: ${{ github.repository_owner }}
          repositories: kubernetes-manifest
      - name: Trigger Renovate
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.get_token.outputs.token }}
          repository: ${{ github.repository_owner }}/kubernetes-manifest
          event-type: renovate
          client-payload: |- # language: json
            {
              "images": "ghcr.io/${{ github.repository_owner }}/${{ inputs.images }}",
              "environments": "${{ inputs.environments }}"
            }
