# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: electricilies-electricilies
stringData:
  VNP_SECURE_SECRET: ENC[AES256_GCM,data:K92z+xc8dNWXrfnwy7R0PE+uV5pevIYS+x7dZIYawR8=,iv:OrOL5dts03Mil+P8KpY027uMFrrlYz/Si/FTYihCYH8=,tag:oZhvDRrnyifDiXf57dlatg==,type:str]
  VNP_TMN_CODE: ENC[AES256_GCM,data:J8U324cvj1g=,iv:QlQxR7jQPjifVYekYcN0s8grPxK9ypOXehkoY7oX+mc=,tag:wLTnxXJje5eV63FaOAGR3g==,type:str]
sops:
  age:
    - recipient: age19q9u5nz7xrtd8qxq3n089n663vznw2r3ayzzdc30zxx3jrezaalseupkkv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM3BGcUZmcnNzT0N6NzNw
        UXVSS2Z0VGQyUDRSN0tLRUIxYmpTbHV0WndrCnY1d1M4bURKTVZRam0xTy9WSnhU
        TUVPb051bWlaWTdUVElzcnpPMzEwYVUKLS0tIHVyVGJCTXA4YnNZMnlWV3pkMFZD
        TUhQdGw4NFhVaUlPSzQ5R1ZSVzdkc00K4svQhxRNUm5Tz+10g+lo6XJA8EkENIuQ
        zXxxIm/C31iUgpwt0TzsV/tWnajGbqs5G6o0yeZHr2BQHHZDFeGkHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T03:38:33Z"
  mac: ENC[AES256_GCM,data:wmGfsBJUczA+ww8jwcQZjaWFoYzqVulotU0oi72F6gEkUkugQY5QqE9TKYsUZAVGwsHl7Q6pGMytAoKxsaRnF90yhZuI7QUVjihks5RWWILuuGOv9BB9Q4GwRINVJPtNI5izCW6mLNNLj5mf6jaJZO9YP7T6B+1RZPioyDnwhu8=,iv:cTCtvp+HF/eILVqJY94Zj31biXXZLCLsb+b+4/wASok=,tag:BXYkPZMj1pYQ9uO7KAlOUw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
