---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: electricilies-dev-backend
resources:
  - ../../../base/backend/electricilies/
  - ./httproute.yaml
patches:
  - path: ./deployment.patch.yaml
  - path: ./keycloak.secret.patch.sops.yaml
images:
  - name: ghcr.io/electricilies/backend
    digest: sha256:0ee5ac9eb2343d1aec031f369a84578c651fc6cc0496d83828517d6d0c67f4cd
